#!/usr/bin/python
# -*- coding: utf-8 -*-
conf_list = [{"ccf":"b","type":"conference","dblp_name":"WWW"},
{"ccf":"c","type":"conference","dblp_name":"WSDM"},
{"ccf":"c","type":"conference","dblp_name":"WOWMOM"},
{"ccf":"c","type":"conference","dblp_name":"WISEC"},
{"ccf":"c","type":"conference","dblp_name":"WISE"},
{"ccf":"c","type":"conference","dblp_name":"WebDB"},
{"ccf":"b","type":"conference","dblp_name":"WCRE"},
{"ccf":"c","type":"conference","dblp_name":"WCNC"},
{"ccf":"c","type":"conference","dblp_name":"WAIM"},
{"ccf":"c","type":"conference","dblp_name":"VTS"},
{"ccf":"b","type":"conference","dblp_name":"VMCAI"},
{"ccf":"b","type":"conference","dblp_name":"VEE"},
{"ccf":"a","type":"conference","dblp_name":"USENIX Security Symposium"},
{"ccf":"b","type":"conference","dblp_name":"USENIX Annual Technical Conference"},
{"ccf":"b","type":"conference","dblp_name":"UIST"},
{"ccf":"c","type":"conference","dblp_name":"UIC/ATC"},
{"ccf":"a","type":"conference","dblp_name":"UbiComp"},
{"ccf":"b","type":"conference","dblp_name":"UAI"},
{"ccf":"c","type":"conference","dblp_name":"TrustCom"},
{"ccf":"c","type":"conference","dblp_name":"TOOLS"},
{"ccf":"b","type":"conference","dblp_name":"TCC"},
{"ccf":"c","type":"conference","dblp_name":"TASE"},
{"ccf":"b","type":"conference","dblp_name":"Symposium on Computational Geometry"},
{"ccf":"a","type":"conference","dblp_name":"STOC"},
{"ccf":"c","type":"conference","dblp_name":"STACS"},
{"ccf":"c","type":"conference","dblp_name":"SSTD"},
{"ccf":"c","type":"conference","dblp_name":"SSDBM"},
{"ccf":"b","type":"conference","dblp_name":"SRDS"},
{"ccf":"c","type":"conference","dblp_name":"SPIN"},
{"ccf":"b","type":"conference","dblp_name":"SPAA"},
{"ccf":"c","type":"conference","dblp_name":"SOUPS"},
{"ccf":"a","type":"conference","dblp_name":"SOSP"},
{"ccf":"b","type":"conference","dblp_name":"SODA"},
{"ccf":"a","type":"conference","dblp_name":"SIGSOFT FSE"},
{"ccf":"b","type":"conference","dblp_name":"SIGMETRICS"},
{"ccf":"a","type":"conference","dblp_name":"SIGIR"},
{"ccf":"a","type":"conference","dblp_name":"SIGGRAPH"},
{"ccf":"a","type":"conference","dblp_name":"SIGCOMM"},
{"ccf":"c","type":"conference","dblp_name":"Shape Modeling International"},
{"ccf":"b","type":"conference","dblp_name":"SenSys"},
{"ccf":"c","type":"conference","dblp_name":"Selected Areas in Cryptography"},
{"ccf":"c","type":"conference","dblp_name":"SEKE"},
{"ccf":"c","type":"conference","dblp_name":"SecureComm"},
{"ccf":"b","type":"conference","dblp_name":"SECON"},
{"ccf":"c","type":"conference","dblp_name":"SEC"},
{"ccf":"b","type":"conference","dblp_name":"SDM"},
{"ccf":"c","type":"conference","dblp_name":"SCAM"},
{"ccf":"b","type":"conference","dblp_name":"SC"},
{"ccf":"c","type":"conference","dblp_name":"SAT"},
{"ccf":"b","type":"conference","dblp_name":"SAS"},
{"ccf":"c","type":"conference","dblp_name":"SACMAT"},
{"ccf":"a","type":"conference","dblp_name":"RTSS"},
{"ccf":"c","type":"conference","dblp_name":"RTA"},
{"ccf":"a","type":"conference","dblp_name":"RED"},
{"ccf":"b","type":"conference","dblp_name":"RECOMB"},
{"ccf":"b","type":"conference","dblp_name":"RAID"},
{"ccf":"c","type":"conference","dblp_name":"QSIC"},
{"ccf":"b","type":"conference","dblp_name":"Public Key Cryptography"},
{"ccf":"c","type":"conference","dblp_name":"PRICAI"},
{"ccf":"b","type":"conference","dblp_name":"PPOPP"},
{"ccf":"a","type":"conference","dblp_name":"POPL"},
{"ccf":"b","type":"conference","dblp_name":"PODS"},
{"ccf":"b","type":"conference","dblp_name":"PODC"},
{"ccf":"b","type":"conference","dblp_name":"Performance"},
{"ccf":"c","type":"conference","dblp_name":"PerCom"},
{"ccf":"c","type":"conference","dblp_name":"PEPM"},
{"ccf":"c","type":"conference","dblp_name":"PCM"},
{"ccf":"c","type":"conference","dblp_name":"PASTE"},
{"ccf":"c","type":"conference","dblp_name":"PAKDD"},
{"ccf":"b","type":"conference","dblp_name":"PACT"},
{"ccf":"c","type":"conference","dblp_name":"PacificVis"},
{"ccf":"c","type":"conference","dblp_name":"P2P"},
{"ccf":"a","type":"conference","dblp_name":"OSDI"},
{"ccf":"a","type":"conference","dblp_name":"OOPSLA"},
{"ccf":"c","type":"conference","dblp_name":"NSPW"},
{"ccf":"b","type":"conference","dblp_name":"NSDI"},
{"ccf":"c","type":"conference","dblp_name":"NPC"},
{"ccf":"b","type":"conference","dblp_name":"NOSSDAV"},
{"ccf":"c","type":"conference","dblp_name":"NOMS"},
{"ccf":"c","type":"conference","dblp_name":"NOCS"},
{"ccf":"b","type":"conference","dblp_name":"NIPS"},
{"ccf":"c","type":"conference","dblp_name":"Networking"},
{"ccf":"b","type":"conference","dblp_name":"NDSS"},
{"ccf":"c","type":"conference","dblp_name":"MSWiM"},
{"ccf":"b","type":"conference","dblp_name":"MSST"},
{"ccf":"b","type":"conference","dblp_name":"MoDELS"},
{"ccf":"b","type":"conference","dblp_name":"MobiSys"},
{"ccf":"c","type":"conference","dblp_name":"MobiQuitous"},
{"ccf":"b","type":"conference","dblp_name":"Mobile HCI"},
{"ccf":"b","type":"conference","dblp_name":"MobiHoc"},
{"ccf":"a","type":"conference","dblp_name":"MOBICOM"},
{"ccf":"c","type":"conference","dblp_name":"MMM"},
{"ccf":"c","type":"conference","dblp_name":"MM&Sec"},
{"ccf":"b","type":"conference","dblp_name":"Middleware"},
{"ccf":"a","type":"conference","dblp_name":"MICRO"},
{"ccf":"c","type":"conference","dblp_name":"MFCS"},
{"ccf":"c","type":"conference","dblp_name":"MDM"},
{"ccf":"c","type":"conference","dblp_name":"MASS"},
{"ccf":"c","type":"conference","dblp_name":"MASCOTS"},
{"ccf":"c","type":"conference","dblp_name":"LOPSTR"},
{"ccf":"b","type":"conference","dblp_name":"LISA"},
{"ccf":"a","type":"conference","dblp_name":"LICS"},
{"ccf":"b","type":"conference","dblp_name":"LCTES"},
{"ccf":"c","type":"conference","dblp_name":"LCN"},
{"ccf":"c","type":"conference","dblp_name":"KSEM"},
{"ccf":"b","type":"conference","dblp_name":"KR"},
{"ccf":"a","type":"conference","dblp_name":"KDD"},
{"ccf":"b","type":"conference","dblp_name":"IWQoS"},
{"ccf":"b","type":"conference","dblp_name":"IUI"},
{"ccf":"b","type":"conference","dblp_name":"ITS"},
{"ccf":"c","type":"conference","dblp_name":"ITC"},
{"ccf":"b","type":"conference","dblp_name":"ISWC"},
{"ccf":"b","type":"conference","dblp_name":"ISSTA"},
{"ccf":"b","type":"conference","dblp_name":"ISSRE"},
{"ccf":"c","type":"conference","dblp_name":"ISPD"},
{"ccf":"c","type":"conference","dblp_name":"ISPASS"},
{"ccf":"b","type":"conference","dblp_name":"ISMB (Supplement of Bioinformatics)"},
{"ccf":"c","type":"conference","dblp_name":"ISMAR"},
{"ccf":"c","type":"conference","dblp_name":"ISLPED"},
{"ccf":"c","type":"conference","dblp_name":"ISCC"},
{"ccf":"c","type":"conference","dblp_name":"ISCAS"},
{"ccf":"a","type":"conference","dblp_name":"ISCA"},
{"ccf":"c","type":"conference","dblp_name":"ISC"},
{"ccf":"c","type":"conference","dblp_name":"ISAAC"},
{"ccf":"b","type":"conference","dblp_name":"IPSN"},
{"ccf":"b","type":"conference","dblp_name":"IPDPS"},
{"ccf":"c","type":"conference","dblp_name":"IPCO"},
{"ccf":"c","type":"conference","dblp_name":"IPCCC"},
{"ccf":"b","type":"conference","dblp_name":"Internet Measurement Conference"},
{"ccf":"c","type":"conference","dblp_name":"INTERACT"},
{"ccf":"c","type":"conference","dblp_name":"Integrated Network Management"},
{"ccf":"a","type":"conference","dblp_name":"INFOCOM"},
{"ccf":"c","type":"conference","dblp_name":"ILP"},
{"ccf":"c","type":"conference","dblp_name":"IJCNN"},
{"ccf":"a","type":"conference","dblp_name":"IJCAI"},
{"ccf":"a","type":"conference","dblp_name":"IEEE Visualization"},
{"ccf":"a","type":"conference","dblp_name":"IEEE Symposium on Security and Privacy"},
{"ccf":"c","type":"conference","dblp_name":"IEEE SCC"},
{"ccf":"b","type":"conference","dblp_name":"IEEE Real-Time and Embedded Technology and Applications Symposium"},
{"ccf":"b","type":"conference","dblp_name":"IEEE Conference on Computational Complexity"},
{"ccf":"c","type":"conference","dblp_name":"IDC"},
{"ccf":"b","type":"conference","dblp_name":"ICWS"},
{"ccf":"c","type":"conference","dblp_name":"ICWE"},
{"ccf":"c","type":"conference","dblp_name":"ICTAI"},
{"ccf":"c","type":"conference","dblp_name":"ICST"},
{"ccf":"c","type":"conference","dblp_name":"ICSSP"},
{"ccf":"c","type":"conference","dblp_name":"ICSR"},
{"ccf":"b","type":"conference","dblp_name":"ICSOC"},
{"ccf":"b","type":"conference","dblp_name":"ICSM"},
{"ccf":"a","type":"conference","dblp_name":"ICSE"},
{"ccf":"b","type":"conference","dblp_name":"ICS"},
{"ccf":"b","type":"conference","dblp_name":"ICRA"},
{"ccf":"c","type":"conference","dblp_name":"ICPR"},
{"ccf":"b","type":"conference","dblp_name":"ICPP"},
{"ccf":"b","type":"conference","dblp_name":"ICPC"},
{"ccf":"c","type":"conference","dblp_name":"ICPADS"},
{"ccf":"c","type":"conference","dblp_name":"ICONIP"},
{"ccf":"b","type":"conference","dblp_name":"ICNP"},
{"ccf":"a","type":"conference","dblp_name":"ICML"},
{"ccf":"c","type":"conference","dblp_name":"ICMI"},
{"ccf":"c","type":"conference","dblp_name":"ICIP "},
{"ccf":"b","type":"conference","dblp_name":"ICFP"},
{"ccf":"c","type":"conference","dblp_name":"ICFEM"},
{"ccf":"c","type":"conference","dblp_name":"ICECCS"},
{"ccf":"b","type":"conference","dblp_name":"ICDT"},
{"ccf":"b","type":"conference","dblp_name":"ICDM"},
{"ccf":"a","type":"conference","dblp_name":"ICDE"},
{"ccf":"b","type":"conference","dblp_name":"ICDCS"},
{"ccf":"c","type":"conference","dblp_name":"ICDAR"},
{"ccf":"a","type":"conference","dblp_name":"ICCV"},
{"ccf":"b","type":"conference","dblp_name":"ICCD"},
{"ccf":"c","type":"conference","dblp_name":"ICCCN"},
{"ccf":"b","type":"conference","dblp_name":"ICCBR"},
{"ccf":"b","type":"conference","dblp_name":"ICCAD"},
{"ccf":"c","type":"conference","dblp_name":"ICC"},
{"ccf":"c","type":"conference","dblp_name":"ICB"},
{"ccf":"c","type":"conference","dblp_name":"ICASSP"},
{"ccf":"b","type":"conference","dblp_name":"ICAPS"},
{"ccf":"c","type":"conference","dblp_name":"ICANN"},
{"ccf":"b","type":"conference","dblp_name":"ICALP"},
{"ccf":"c","type":"conference","dblp_name":"ICA3PP"},
{"ccf":"b","type":"conference","dblp_name":"HPDC"},
{"ccf":"c","type":"conference","dblp_name":"HPCC"},
{"ccf":"a","type":"conference","dblp_name":"HPCA"},
{"ccf":"b","type":"conference","dblp_name":"HotOS"},
{"ccf":"c","type":"conference","dblp_name":"HotNets"},
{"ccf":"c","type":"conference","dblp_name":"Hot Interconnects"},
{"ccf":"c","type":"conference","dblp_name":"HLT-NAACL"},
{"ccf":"b","type":"conference","dblp_name":"HiPEAC"},
{"ccf":"c","type":"conference","dblp_name":"HiPC"},
{"ccf":"c","type":"conference","dblp_name":"GROUP"},
{"ccf":"c","type":"conference","dblp_name":"Graphics Interface"},
{"ccf":"c","type":"conference","dblp_name":"GMP"},
{"ccf":"c","type":"conference","dblp_name":"GLOBECOM"},
{"ccf":"c","type":"conference","dblp_name":"GECCO"},
{"ccf":"c","type":"conference","dblp_name":"FSTTCS"},
{"ccf":"b","type":"conference","dblp_name":"FSE"},
{"ccf":"c","type":"conference","dblp_name":"FPT"},
{"ccf":"c","type":"conference","dblp_name":"FPL"},
{"ccf":"b","type":"conference","dblp_name":"FPGA"},
{"ccf":"c","type":"conference","dblp_name":"FORTE"},
{"ccf":"a","type":"conference","dblp_name":"FOCS"},
{"ccf":"c","type":"conference","dblp_name":"FMCAD"},
{"ccf":"b","type":"conference","dblp_name":"FM+AM"},
{"ccf":"c","type":"conference","dblp_name":"Financial Cryptography"},
{"ccf":"c","type":"conference","dblp_name":"FG"},
{"ccf":"c","type":"conference","dblp_name":"FCCM"},
{"ccf":"a","type":"conference","dblp_name":"FAST"},
{"ccf":"b","type":"conference","dblp_name":"EuroSys"},
{"ccf":"c","type":"conference","dblp_name":"European Test Symposium"},
{"ccf":"a","type":"conference","dblp_name":"EUROCRYPT"},
{"ccf":"c","type":"conference","dblp_name":"Euro-Par"},
{"ccf":"c","type":"conference","dblp_name":"ESWC"},
{"ccf":"b","type":"conference","dblp_name":"ESORICS"},
{"ccf":"c","type":"conference","dblp_name":"ESEM"},
{"ccf":"c","type":"conference","dblp_name":"ESA"},
{"ccf":"b","type":"conference","dblp_name":"ER@BR"},
{"ccf":"c","type":"conference","dblp_name":"ER Workshops"},
{"ccf":"b","type":"conference","dblp_name":"EMSOFT"},
{"ccf":"b","type":"conference","dblp_name":"EMNLP-CoNLL"},
{"ccf":"b","type":"conference","dblp_name":"EDBT"},
{"ccf":"b","type":"conference","dblp_name":"ECSCW"},
{"ccf":"b","type":"conference","dblp_name":"ECOOP"},
{"ccf":"b","type":"conference","dblp_name":"ECML"},
{"ccf":"c","type":"conference","dblp_name":"ECIR"},
{"ccf":"b","type":"conference","dblp_name":"ECCV"},
{"ccf":"b","type":"conference","dblp_name":"ECAI"},
{"ccf":"b","type":"conference","dblp_name":"DSN"},
{"ccf":"c","type":"conference","dblp_name":"DIMVA"},
{"ccf":"c","type":"conference","dblp_name":"Digital Rights Management Workshop"},
{"ccf":"c","type":"conference","dblp_name":"DFRWS"},
{"ccf":"c","type":"conference","dblp_name":"DEXA"},
{"ccf":"b","type":"conference","dblp_name":"DATE"},
{"ccf":"b","type":"conference","dblp_name":"DASFAA "},
{"ccf":"b","type":"conference","dblp_name":"DAC"},
{"ccf":"a","type":"conference","dblp_name":"CVPR"},
{"ccf":"c","type":"conference","dblp_name":"CT-RSA"},
{"ccf":"c","type":"conference","dblp_name":"CSL"},
{"ccf":"b","type":"conference","dblp_name":"CSFW"},
{"ccf":"b","type":"conference","dblp_name":"CSCW"},
{"ccf":"a","type":"conference","dblp_name":"CRYPTO"},
{"ccf":"b","type":"conference","dblp_name":"CP"},
{"ccf":"c","type":"conference","dblp_name":"COSIT"},
{"ccf":"c","type":"conference","dblp_name":"CoopIS/DOA/ODBASE"},
{"ccf":"c","type":"conference","dblp_name":"Conference on Designing Interactive Systems"},
{"ccf":"c","type":"conference","dblp_name":"Conf. Computing Frontiers"},
{"ccf":"b","type":"conference","dblp_name":"CoNEXT"},
{"ccf":"b","type":"conference","dblp_name":"CONCUR"},
{"ccf":"c","type":"conference","dblp_name":"COMPSAC"},
{"ccf":"b","type":"conference","dblp_name":"COLT"},
{"ccf":"b","type":"conference","dblp_name":"COLING"},
{"ccf":"c","type":"conference","dblp_name":"CODES+ISSS"},
{"ccf":"c","type":"conference","dblp_name":"CLUSTER"},
{"ccf":"b","type":"conference","dblp_name":"CIKM"},
{"ccf":"b","type":"conference","dblp_name":"CIDR"},
{"ccf":"a","type":"conference","dblp_name":"CHI"},
{"ccf":"b","type":"conference","dblp_name":"CHES"},
{"ccf":"b","type":"conference","dblp_name":"CGO"},
{"ccf":"c","type":"conference","dblp_name":"CCGrid"},
{"ccf":"b","type":"conference","dblp_name":"CC"},
{"ccf":"b","type":"conference","dblp_name":"CAV"},
{"ccf":"c","type":"conference","dblp_name":"CASES"},
{"ccf":"b","type":"conference","dblp_name":"CAiSE"},
{"ccf":"b","type":"conference","dblp_name":"CADE"},
{"ccf":"c","type":"conference","dblp_name":"BMVC"},
{"ccf":"b","type":"conference","dblp_name":"BIBM"},
{"ccf":"a","type":"conference","dblp_name":"Best of PLDI"},
{"ccf":"c","type":"conference","dblp_name":"AVI"},
{"ccf":"c","type":"conference","dblp_name":"ATVA"},
{"ccf":"c","type":"conference","dblp_name":"ASSETS"},
{"ccf":"a","type":"conference","dblp_name":"ASPLOS"},
{"ccf":"c","type":"conference","dblp_name":"ASP-DAC"},
{"ccf":"b","type":"conference","dblp_name":"ASIACRYPT"},
{"ccf":"c","type":"conference","dblp_name":"ASIACCS"},
{"ccf":"b","type":"conference","dblp_name":"ASE"},
{"ccf":"c","type":"conference","dblp_name":"ASAP"},
{"ccf":"c","type":"conference","dblp_name":"APWeb"},
{"ccf":"c","type":"conference","dblp_name":"APSEC"},
{"ccf":"c","type":"conference","dblp_name":"APLAS"},
{"ccf":"c","type":"conference","dblp_name":"APBC"},
{"ccf":"c","type":"conference","dblp_name":"ANCS"},
{"ccf":"c","type":"conference","dblp_name":"ALT"},
{"ccf":"b","type":"conference","dblp_name":"ACSAC"},
{"ccf":"c","type":"conference","dblp_name":"ACNS"},
{"ccf":"a","type":"conference","dblp_name":"ACM SIGMOD Digital Review"},
{"ccf":"a","type":"conference","dblp_name":"ACM Multimedia"},
{"ccf":"c","type":"conference","dblp_name":"ACM Great Lakes Symposium on VLSI"},
{"ccf":"a","type":"conference","dblp_name":"ACM Conference on Computer and Communications Security"},
{"ccf":"b","type":"conference","dblp_name":"ACL"},
{"ccf":"c","type":"conference","dblp_name":"ACISP"},
{"ccf":"c","type":"conference","dblp_name":"ACCV"},
{"ccf":"b","type":"conference","dblp_name":"AAMAS"},
{"ccf":"a","type":"conference","dblp_name":"AAAI"}]

jour_list = [{"ccf":"c","type":"journel","dblp_name":"Web Intelligence and Agent Systems"},
{"ccf":"a","type":"journel","dblp_name":"VLDB J."},
{"ccf":"b","type":"journel","dblp_name":"User Model. User-Adapt. Interact."},
{"ccf":"b","type":"journel","dblp_name":"TWEB"},
{"ccf":"b","type":"journel","dblp_name":"TSLP"},
{"ccf":"b","type":"journel","dblp_name":"TRETS"},
{"ccf":"c","type":"journel","dblp_name":"TPLP"},
{"ccf":"b","type":"journel","dblp_name":"TOS"},
{"ccf":"b","type":"journel","dblp_name":"TOMCCAP"},
{"ccf":"b","type":"journel","dblp_name":"TKDD"},
{"ccf":"c","type":"journel","dblp_name":"Theory Comput. Syst."},
{"ccf":"b","type":"journel","dblp_name":"Theor. Comput. Sci."},
{"ccf":"c","type":"journel","dblp_name":"The Visual Computer"},
{"ccf":"c","type":"journel","dblp_name":"The Journal of Supercomputing"},
{"ccf":"b","type":"journel","dblp_name":"TAP"},
{"ccf":"b","type":"journel","dblp_name":"TACO"},
{"ccf":"b","type":"journel","dblp_name":"TAAS"},
{"ccf":"b","type":"journel","dblp_name":"T. Affective Computing"},
{"ccf":"c","type":"journel","dblp_name":"STTT"},
{"ccf":"b","type":"journel","dblp_name":"Speech Communication"},
{"ccf":"c","type":"journel","dblp_name":"Software Quality Journal"},
{"ccf":"b","type":"journel","dblp_name":"Software and System Modeling"},
{"ccf":"b","type":"journel","dblp_name":"Softw., Pract. Exper."},
{"ccf":"b","type":"journel","dblp_name":"Softw. Test., Verif. Reliab."},
{"ccf":"c","type":"journel","dblp_name":"Soft Comput."},
{"ccf":"c","type":"journel","dblp_name":"Signal Processing"},
{"ccf":"c","type":"journel","dblp_name":"Sig. Proc.: Image Comm."},
{"ccf":"b","type":"journel","dblp_name":"SIAM J. Imaging Sciences"},
{"ccf":"c","type":"journel","dblp_name":"SIAM J. Discrete Math."},
{"ccf":"a","type":"journel","dblp_name":"SIAM J. Comput."},
{"ccf":"c","type":"journel","dblp_name":"Service Oriented Computing and Applications"},
{"ccf":"c","type":"journel","dblp_name":"Security and Communication Networks"},
{"ccf":"b","type":"journel","dblp_name":"SCIENCE CHINA Information Sciences"},
{"ccf":"b","type":"journel","dblp_name":"Sci. Comput. Program."},
{"ccf":"b","type":"journel","dblp_name":"Requir. Eng."},
{"ccf":"a","type":"journel","dblp_name":"Proceedings of the IEEE"},
{"ccf":"b","type":"journel","dblp_name":"PLoS Computational Biology"},
{"ccf":"c","type":"journel","dblp_name":"Pervasive and Mobile Computing"},
{"ccf":"c","type":"journel","dblp_name":"Personal and Ubiquitous Computing"},
{"ccf":"b","type":"journel","dblp_name":"Perform. Eval."},
{"ccf":"c","type":"journel","dblp_name":"Pattern Recognition Letters"},
{"ccf":"b","type":"journel","dblp_name":"Pattern Recognition"},
{"ccf":"c","type":"journel","dblp_name":"Pattern Anal. Appl."},
{"ccf":"b","type":"journel","dblp_name":"Parallel Computing"},
{"ccf":"c","type":"journel","dblp_name":"Neurocomputing"},
{"ccf":"c","type":"journel","dblp_name":"Neural Processing Letters"},
{"ccf":"b","type":"journel","dblp_name":"Neural Networks"},
{"ccf":"c","type":"journel","dblp_name":"Neural Computing and Applications"},
{"ccf":"b","type":"journel","dblp_name":"Neural Computation"},
{"ccf":"c","type":"journel","dblp_name":"Natural Language Engineering"},
{"ccf":"c","type":"journel","dblp_name":"Natural Computing"},
{"ccf":"c","type":"journel","dblp_name":"Multimedia Tools Appl."},
{"ccf":"c","type":"journel","dblp_name":"Multimedia Syst."},
{"ccf":"c","type":"journel","dblp_name":"Microprocessors and Microsystems - Embedded Hardware Design"},
{"ccf":"c","type":"journel","dblp_name":"Medical Image Analysis"},
{"ccf":"b","type":"journel","dblp_name":"Mathematical Structures in Computer Science"},
{"ccf":"c","type":"journel","dblp_name":"Machine Translation"},
{"ccf":"b","type":"journel","dblp_name":"Machine Learning"},
{"ccf":"c","type":"journel","dblp_name":"Mach. Vis. Appl."},
{"ccf":"c","type":"journel","dblp_name":"Logical Methods in Computer Science"},
{"ccf":"c","type":"journel","dblp_name":"Knowl.-Based Syst."},
{"ccf":"b","type":"journel","dblp_name":"Knowl. Inf. Syst."},
{"ccf":"c","type":"journel","dblp_name":"Journal of Systems Architecture - Embedded Systems Design"},
{"ccf":"b","type":"journel","dblp_name":"Journal of Systems and Software"},
{"ccf":"b","type":"journel","dblp_name":"Journal of Software: Evolution and Process"},
{"ccf":"a","type":"journel","dblp_name":"Journal of Machine Learning Research"},
{"ccf":"b","type":"journel","dblp_name":"Journal of Computer Security"},
{"ccf":"c","type":"journel","dblp_name":"JGIM"},
{"ccf":"c","type":"journel","dblp_name":"JETC"},
{"ccf":"b","type":"journel","dblp_name":"JASIST"},
{"ccf":"b","type":"journel","dblp_name":"JAMIA"},
{"ccf":"b","type":"journel","dblp_name":"J. Web Sem."},
{"ccf":"c","type":"journel","dblp_name":"J. Web Eng."},
{"ccf":"c","type":"journel","dblp_name":"J. Visual Communication and Image Representation"},
{"ccf":"c","type":"journel","dblp_name":"J. Symb. Log."},
{"ccf":"b","type":"journel","dblp_name":"J. Symb. Comput."},
{"ccf":"c","type":"journel","dblp_name":"J. Strategic Inf. Sys."},
{"ccf":"b","type":"journel","dblp_name":"J. Parallel Distrib. Comput."},
{"ccf":"c","type":"journel","dblp_name":"J. Log. Comput."},
{"ccf":"c","type":"journel","dblp_name":"J. Log. Algebr. Program."},
{"ccf":"c","type":"journel","dblp_name":"J. Intell. Inf. Syst."},
{"ccf":"c","type":"journel","dblp_name":"J. Grid Comput."},
{"ccf":"b","type":"journel","dblp_name":"J. Global Optimization"},
{"ccf":"b","type":"journel","dblp_name":"J. Funct. Program."},
{"ccf":"c","type":"journel","dblp_name":"J. Exp. Theor. Artif. Intell."},
{"ccf":"c","type":"journel","dblp_name":"J. Electronic Testing"},
{"ccf":"c","type":"journel","dblp_name":"J. Database Manag."},
{"ccf":"a","type":"journel","dblp_name":"J. Cryptology"},
{"ccf":"b","type":"journel","dblp_name":"J. Comput. Syst. Sci."},
{"ccf":"b","type":"journel","dblp_name":"J. Comput. Sci. Technol."},
{"ccf":"c","type":"journel","dblp_name":"J. Complexity"},
{"ccf":"b","type":"journel","dblp_name":"J. Autom. Reasoning"},
{"ccf":"b","type":"journel","dblp_name":"J. Artif. Intell. Res. (JAIR)"},
{"ccf":"a","type":"journel","dblp_name":"J. ACM"},
{"ccf":"c","type":"journel","dblp_name":"International Journal of Uncertainty, Fuzziness and Knowledge-Based Systems"},
{"ccf":"c","type":"journel","dblp_name":"International Journal of Software Engineering and Knowledge Engineering"},
{"ccf":"c","type":"journel","dblp_name":"International Journal of Geographical Information Science"},
{"ccf":"a","type":"journel","dblp_name":"International Journal of Computer Vision"},
{"ccf":"c","type":"journel","dblp_name":"International Journal of Computational Intelligence and Applications"},
{"ccf":"b","type":"journel","dblp_name":"Interacting with Computers"},
{"ccf":"c","type":"journel","dblp_name":"Intell. Data Anal."},
{"ccf":"c","type":"journel","dblp_name":"Integration"},
{"ccf":"c","type":"journel","dblp_name":"Int. J. Semantic Web Inf. Syst."},
{"ccf":"c","type":"journel","dblp_name":"Int. J. Neural Syst."},
{"ccf":"c","type":"journel","dblp_name":"Int. J. Intell. Syst."},
{"ccf":"c","type":"journel","dblp_name":"Int. J. Intell. Syst."},
{"ccf":"a","type":"journel","dblp_name":"Int. J. Hum.-Comput. Stud."},
{"ccf":"c","type":"journel","dblp_name":"Int. J. Hum. Comput. Interaction"},
{"ccf":"c","type":"journel","dblp_name":"Int. J. Cooperative Inf. Syst."},
{"ccf":"b","type":"journel","dblp_name":"Int. J. Approx. Reasoning"},
{"ccf":"b","type":"journel","dblp_name":"INFORMS Journal on Computing"},
{"ccf":"b","type":"journel","dblp_name":"Information & Software Technology"},
{"ccf":"c","type":"journel","dblp_name":"Information & Management"},
{"ccf":"b","type":"journel","dblp_name":"Inf. Syst."},
{"ccf":"c","type":"journel","dblp_name":"Inf. Sec. Techn. Report"},
{"ccf":"b","type":"journel","dblp_name":"Inf. Sci."},
{"ccf":"c","type":"journel","dblp_name":"Inf. Retr."},
{"ccf":"b","type":"journel","dblp_name":"Inf. Process. Manage."},
{"ccf":"c","type":"journel","dblp_name":"Inf. Process. Lett."},
{"ccf":"c","type":"journel","dblp_name":"Inf. Process. Lett."},
{"ccf":"c","type":"journel","dblp_name":"Inf. Manag. Comput. Security"},
{"ccf":"a","type":"journel","dblp_name":"Inf. Comput."},
{"ccf":"c","type":"journel","dblp_name":"Image Vision Comput."},
{"ccf":"c","type":"journel","dblp_name":"IJPRAI"},
{"ccf":"c","type":"journel","dblp_name":"IJKM"},
{"ccf":"c","type":"journel","dblp_name":"IJISP"},
{"ccf":"c","type":"journel","dblp_name":"IJDAR"},
{"ccf":"b","type":"journel","dblp_name":"IET Software"},
{"ccf":"c","type":"journel","dblp_name":"IET Information Security"},
{"ccf":"c","type":"journel","dblp_name":"IEEE/ACM Trans. Comput. Biology Bioinform."},
{"ccf":"b","type":"journel","dblp_name":"IEEE Transactions on Robotics"},
{"ccf":"b","type":"journel","dblp_name":"IEEE Transactions on Multimedia"},
{"ccf":"b","type":"journel","dblp_name":"IEEE Transactions on Intelligent Transportation Systems"},
{"ccf":"c","type":"journel","dblp_name":"IEEE Transactions on Information Technology in Biomedicine"},
{"ccf":"a","type":"journel","dblp_name":"IEEE Transactions on Information Forensics and Security"},
{"ccf":"a","type":"journel","dblp_name":"IEEE Transactions on Image Processing"},
{"ccf":"b","type":"journel","dblp_name":"IEEE Transactions on Audio, Speech & Language Processing"},
{"ccf":"b","type":"journel","dblp_name":"IEEE Trans. VLSI Syst."},
{"ccf":"a","type":"journel","dblp_name":"IEEE Trans. Vis. Comput. Graph."},
{"ccf":"a","type":"journel","dblp_name":"IEEE Trans. Software Eng."},
{"ccf":"a","type":"journel","dblp_name":"IEEE Trans. Pattern Anal. Mach. Intell."},
{"ccf":"a","type":"journel","dblp_name":"IEEE Trans. Parallel Distrib. Syst."},
{"ccf":"b","type":"journel","dblp_name":"IEEE Trans. on CAD of Integrated Circuits and Systems"},
{"ccf":"b","type":"journel","dblp_name":"IEEE Trans. Neural Netw. Learning Syst."},
{"ccf":"b","type":"journel","dblp_name":"IEEE Trans. Med. Imaging"},
{"ccf":"a","type":"journel","dblp_name":"IEEE Trans. Knowl. Data Eng."},
{"ccf":"b","type":"journel","dblp_name":"IEEE Trans. Evolutionary Computation"},
{"ccf":"a","type":"journel","dblp_name":"IEEE Trans. Dependable Sec. Comput."},
{"ccf":"a","type":"journel","dblp_name":"IEEE Trans. Computers"},
{"ccf":"c","type":"journel","dblp_name":"IEEE Trans. Comput. Intellig. and AI in Games"},
{"ccf":"b","type":"journel","dblp_name":"IEEE Trans. Circuits Syst. Video Techn."},
{"ccf":"b","type":"journel","dblp_name":"IEEE T. Services Computing"},
{"ccf":"b","type":"journel","dblp_name":"IEEE T. Geoscience and Remote Sensing"},
{"ccf":"b","type":"journel","dblp_name":"IEEE T. Fuzzy Systems"},
{"ccf":"b","type":"journel","dblp_name":"IEEE T. Automation Science and Engineering"},
{"ccf":"c","type":"journel","dblp_name":"IEEE Signal Process. Lett."},
{"ccf":"c","type":"journel","dblp_name":"IEEE Geosci. Remote Sensing Lett."},
{"ccf":"c","type":"journel","dblp_name":"Higher-Order and Symbolic Computation"},
{"ccf":"b","type":"journel","dblp_name":"Graphical Models"},
{"ccf":"b","type":"journel","dblp_name":"GeoInformatica"},
{"ccf":"c","type":"journel","dblp_name":"Fuzzy Sets and Systems"},
{"ccf":"c","type":"journel","dblp_name":"Future Generation Comp. Syst."},
{"ccf":"c","type":"journel","dblp_name":"Fundam. Inform."},
{"ccf":"c","type":"journel","dblp_name":"Frontiers of Computer Science"},
{"ccf":"b","type":"journel","dblp_name":"Formal Methods in System Design"},
{"ccf":"b","type":"journel","dblp_name":"Formal Asp. Comput."},
{"ccf":"c","type":"journel","dblp_name":"Expert Systems"},
{"ccf":"c","type":"journel","dblp_name":"Expert Syst. Appl."},
{"ccf":"b","type":"journel","dblp_name":"Evolutionary Computation"},
{"ccf":"c","type":"journel","dblp_name":"EURASIP J. Information Security"},
{"ccf":"c","type":"journel","dblp_name":"Eng. Appl. of AI"},
{"ccf":"b","type":"journel","dblp_name":"Empirical Software Engineering"},
{"ccf":"b","type":"journel","dblp_name":"EJIS"},
{"ccf":"c","type":"journel","dblp_name":"Distributed Computing"},
{"ccf":"c","type":"journel","dblp_name":"Distributed and Parallel Databases"},
{"ccf":"c","type":"journel","dblp_name":"Discrete Applied Mathematics"},
{"ccf":"c","type":"journel","dblp_name":"Discrete & Computational Geometry"},
{"ccf":"b","type":"journel","dblp_name":"Des. Codes Cryptography"},
{"ccf":"c","type":"journel","dblp_name":"Decision Support Systems"},
{"ccf":"b","type":"journel","dblp_name":"Data Min. Knowl. Discov."},
{"ccf":"b","type":"journel","dblp_name":"Data Knowl. Eng."},
{"ccf":"b","type":"journel","dblp_name":"Data Knowl. Eng."},
{"ccf":"c","type":"journel","dblp_name":"Cybernetics and Systems"},
{"ccf":"c","type":"journel","dblp_name":"Connect. Sci."},
{"ccf":"c","type":"journel","dblp_name":"Concurrency and Computation: Practice and Experience"},
{"ccf":"b","type":"journel","dblp_name":"Computers & Security"},
{"ccf":"b","type":"journel","dblp_name":"Computer-Aided Design"},
{"ccf":"b","type":"journel","dblp_name":"Computer Vision and Image Understanding"},
{"ccf":"b","type":"journel","dblp_name":"Computer Supported Cooperative Work"},
{"ccf":"c","type":"journel","dblp_name":"Computer Speech & Language"},
{"ccf":"c","type":"journel","dblp_name":"Computer Languages, Systems & Structures"},
{"ccf":"b","type":"journel","dblp_name":"Computer Aided Geometric Design"},
{"ccf":"b","type":"journel","dblp_name":"Computational Linguistics"},
{"ccf":"c","type":"journel","dblp_name":"Computational Intelligence"},
{"ccf":"b","type":"journel","dblp_name":"Computational Complexity"},
{"ccf":"b","type":"journel","dblp_name":"Comput. J."},
{"ccf":"b","type":"journel","dblp_name":"Comput. Graph. Forum"},
{"ccf":"c","type":"journel","dblp_name":"Comput. Geom."},
{"ccf":"b","type":"journel","dblp_name":"Cognitive Science"},
{"ccf":"a","type":"journel","dblp_name":"CCTA"},
{"ccf":"b","type":"journel","dblp_name":"Briefings in Bioinformatics"},
{"ccf":"c","type":"journel","dblp_name":"BMC Bioinformatics"},
{"ccf":"b","type":"journel","dblp_name":"Bioinformatics"},
{"ccf":"c","type":"journel","dblp_name":"Behaviour & IT"},
{"ccf":"c","type":"journel","dblp_name":"Autonomous Agents and Multi-Agent Systems"},
{"ccf":"b","type":"journel","dblp_name":"Autom. Softw. Eng."},
{"ccf":"c","type":"journel","dblp_name":"Artificial Life"},
{"ccf":"c","type":"journel","dblp_name":"Artificial Intelligence in Medicine"},
{"ccf":"c","type":"journel","dblp_name":"Appl. Intell."},
{"ccf":"c","type":"journel","dblp_name":"Ann. Pure Appl. Logic"},
{"ccf":"b","type":"journel","dblp_name":"Algorithmica"},
{"ccf":"b","type":"journel","dblp_name":"Advanced Engineering Informatics"},
{"ccf":"c","type":"journel","dblp_name":"Acta Inf."},
{"ccf":"b","type":"journel","dblp_name":"ACM Transactions on Algorithms"},
{"ccf":"a","type":"journel","dblp_name":"ACM Trans. Softw. Eng. Methodol."},
{"ccf":"a","type":"journel","dblp_name":"ACM Trans. Program. Lang. Syst."},
{"ccf":"b","type":"journel","dblp_name":"ACM Trans. Math. Softw."},
{"ccf":"b","type":"journel","dblp_name":"ACM Trans. Inf. Syst. Secur."},
{"ccf":"a","type":"journel","dblp_name":"ACM Trans. Inf. Syst."},
{"ccf":"a","type":"journel","dblp_name":"ACM Trans. Graph."},
{"ccf":"b","type":"journel","dblp_name":"ACM Trans. Embedded Comput. Syst."},
{"ccf":"b","type":"journel","dblp_name":"ACM Trans. Design Autom. Electr. Syst."},
{"ccf":"a","type":"journel","dblp_name":"ACM Trans. Database Syst."},
{"ccf":"a","type":"journel","dblp_name":"ACM Trans. Comput.-Hum. Interact."},
{"ccf":"a","type":"journel","dblp_name":"ACM Trans. Comput. Syst."},
{"ccf":"b","type":"journel","dblp_name":"ACM Trans. Comput. Log."},
{"ccf":"c","type":"journel","dblp_name":"ACM Trans. Asian Lang. Inf. Process."}]
