#!/usr/bin/python
# -*- coding: utf-8 -*-

patent_list=[
{
'num':u'申请号:',
'numan':u'CN201220548519 ',  
'pubnum':u'公开号:',
'pubnuman':u'CN202856795',
'name':u'专利名称:',
'namean':u'用于物联网存储的<strong class="text-error">云计算</strong>基础架构系统',
'person':u'申请人:',
'personan':u'江苏物联网研究发展中心',
'invent':u'发明人:',
'inventan':u'葛浩栋;陈曙东',
'explain':u'专利说明:',
'explainan':u'本实用新型提供一种用于物联网存储的<strong class="text-error">云计算</strong>基础架构系统，其特征在于：包括云操作系统及应用接口、<strong class="text-error">云计算</strong>子系统节点、云文件子系统节点、计算资源池节点、大数据存储池节点、小数据存储池节点、计算与存储资源虚拟化节点、集群计算服务器组、集群存储服务器组；集群计算服务器组、集群存储服务器组上的计算与存储资源地址由计算与存储资源虚拟化节点映射至由服务器构成的计算资源池节点、大数据存储池节点、小数据存储池节点上；本实用新型用于物联网的海量数据的存储和<strong class="text-error">云计算</strong>。',
},
{
'num':u'申请号:',
'numan':u'CN200920176903 ',  
'pubnum':u'公开号:',
'pubnuman':u'CN201532634',
'name':u'专利名称:',
'namean':u'基于不可信服务器节点的<strong class="text-error">云计算</strong>基础架构系统',
'person':u'申请人:',
'personan':u'王鹏',
'invent':u'发明人:',
'inventan':u'王鹏',
'explain':u'专利说明：',
'explainan':u'本实用新型涉及<strong class="text-error">云计算</strong>基础架构系统，尤其涉及基于不可信服务器节点的<strong class="text-error">云计算</strong>基础架构系统。基于不可信服务器节点的<strong class="text-error">云计算</strong>基础架构系统，其特征在于：该系统包括云操作系统及API接口、隔离节点失效模块、计算层系统、云分布式文件系统、计算和存储虚拟化模块、网络机群、操作系统、不可信服务器组成，所述的云操作系统及API接口与隔离节点失效模块连接，隔离节点失效模块与计算层系统连接、计算层系统与云分布式文件系统连接、云分布式文件系统与计算和存储虚拟化模块连接、计算和存储虚拟化模块与网络机群连接、网络机群与操作系统连接、网络机群与不可信服务器连接。',
},
{
'num':u'申请号:',
'numan':u'CN201110394034 ',  
'pubnum':u'公开号:',
'pubnuman':u'CN102368787',
'name':u'专利名称:',
'namean':u'一种基于KVM虚拟化和媒体重定向的<strong class="text-error">云计算</strong>系统',
'person':u'申请人:',
'personan':u'浪潮集团有限公司',
'invent':u'发明人:',
'inventan':u'金长新;刘强;梁智豪',
'explain':u'专利说明：',
'explainan':u'本发明公开了一种基于KVM虚拟化和媒体重定向的<strong class="text-error">云计算</strong>系统。系统中包含两部分<strong class="text-error">云计算</strong>服务器端和客户端。服务器端除实现资源的虚拟化外还实现了KVM的虚拟化以及媒体重定向的虚拟化。资源虚拟化单元为用户提供CPU、内存等计算资源；KVM虚拟化为用户提供VIDEO视频显示、键盘及鼠标等人机交互模式；媒体重定向单元可以将用户端的光驱、软盘、U盘等存储设备映射到服务器端，供用户数据的传输。这样对用户端来说通过这三个虚拟化部分就组成了用户端的一个完整的计算机虚拟设备，减小客户端硬件资源的需求，方便服务器端云计算服务的构建。',
},
{
'num':u'申请号:',
'numan':u'CN201210067011 ',  
'pubnum':u'公开号:',
'pubnuman':u'CN102624732',
'name':u'专利名称:',
'namean':u'一种基于<strong class="text-error">云计算</strong>的网络存储系统',
'person':u'申请人:',
'personan':u'上海华御信息技术有限公司',
'invent':u'发明人:',
'inventan':u'曾曙;刘旭峰',
'explain':u'专利说明：',
'explainan':u'本发明公开了一种基于<strong class="text-error">云计算</strong>的网络存储系统，包括：云存储代理节点、云存储节点、云存储软件，所述云存储代理节点只存储各节点的虚拟路径，当用户需要访问某一文件时，代理节点即按照预置的虚拟路径去获取文件以供用户去使用。所述云存储代理节点即用户日常所使用的各类PC、智能终端等，只需要能够提供用户所需要的存储空间即可并带有智能操作系统。本发明通过将用户指定的网络存储地址虚拟化，并配合一定的加密机制，这样只要有网络用户就可以访问自己的文件，方便快捷，解决不同介质之间数据共享的问题。'
},

]